import Head from "next/head";
import Header from "@/components/loyaut/header.jsx";
import Footer from "@/components/loyaut/footer.jsx";
import Front from "@/components/sections/front/front.jsx";
import Products from "@/components/sections/products/products.jsx";
import Formats from "@/components/sections/formats/formats.jsx";
import Commission from "@/components/sections/commission/commission.jsx";
import Benefits from "@/components/sections/benefits/benefits.jsx";
import Faq from "@/components/sections/faq/faq.jsx";
import Contacts from "@/components/sections/contacts/contacts.jsx";


export default function Home() {
  
const jsonLdOrganization = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Xpicture AI",
  url: "https://xpicture.ai/",
  logo: "",
  alternateName: "xpicture ai undresser"
}


const jsonLdWebPage = {
  "@context": "https://schema.org/",
  "@type": "WebSite",
  "name": "Xpicture AI Undresser",
  "url": "https://xpicture.ai/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "{search_term_string}",
    "query-input": "required name=search_term_string"
  }
}

  return (
    <>
      <Head>
        <title>X-ADS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow"></meta>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&family=Lora:ital,wght@0,400..700;1,400..700&family=Manrope:wght@200..800&family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playfair:ital,opsz,wght@0,5..1200,300..900;1,5..1200,300..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Sora:wght@100..800&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&family=Lora:ital,wght@0,400..700;1,400..700&family=Manrope:wght@200..800&family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playfair:ital,opsz,wght@0,5..1200,300..900;1,5..1200,300..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&family=Sora:wght@100..800&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type='application/ld+json'
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(jsonLdOrganization),
          }}
        />
        <script
          type='application/ld+json'
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdWebPage) }}
        />
      </Head>
      
      <Header />
      <main>
        <Front />
        <Products />
        {/* <Formats /> */}
        <Commission />
        <Benefits />
        <Faq />
        <Contacts />
      </main>
      <Footer />
    </>
  );
}
